const data = {
  SELF_ACTIVATION: "အကောင့်ဖွင့်ရန်",
  YOMA_BANK_ACCOUNT_AND_NRC_OR_PASSPORT_NUMBER:
    "သင်၏ရိုးမဘဏ်အကောင့်နှင့် မှတ်ပုံတင်နံပါတ် သို့မဟုတ် နိုင်ငံကူးလက်မှတ်ထည့်ရန်",
  PROVIDE_INFORMATION_TO_REGISTER:
    "စာရင်းသွင်းရန် အောက်ပါအချက်များကို ဖြည့်စွက်ပါ",
  ACCOUNT_NUMBER: "Account Number",
  ENTER_DIGITS: "နံပါတ်ထည့်ပါ",
  PASSPORT_OR_6_DIGITS_OF_YOUR_NRC_NUMBER:
    "ပတ်စ်ပို့  (သို့) မှတ်ပုံတင်နံပါတ် ၆ လုံး",
  ENTER_PASSPORT_OR_NRC: "ပတ်စ်ပို့ (သို့) မှတ်ပုံတင်နံပါတ် ရိုက်ထည့်ပါ",
  I_AGREE_OF_TERMS_AND_CONDITIONS: "{{value}} သဘောတူပါသည်",
  TERMS_AND_CONDITIONS: "စည်းကမ်းများနှင့် လက်ခံမှုများ",
  NEXT: "ဆက်သွားမည်",
  ENTER_VERIFICATION_CODE: "အတည်ပြုကုတ်နံပါတ် ထည့်ပါ",
  PLEASE_ENTER_THE_VERIFICATION_CODE_SEND_TO_REGISTER_PHONE_NUMBER:
    "ဘဏ်အကောင့်ဖွင့်စဉ်က စာရင်းသွင်းထားသည့် ဖုန်းနံပါတ် {{value}} သို့ ပေးပို့ထားသောအတည်ပြုကုတ်နံပါတ်ကို ထည့်ပါ",
  VERIFICATION_CODE: "အတည်ပြုကုတ်နံပါတ်",
  ENTER_6_DIGIT_CODE: "ကုတ်နံပါတ် ၆ လုံးကို ထည့်ပါ",
  OTP_WILL_BE_EXPIRED_IN: "{{value}} တွင် OTP သက်တမ်းကုန်ဆုံးပါမည်",
  DONT_RECEIVE_THE_OTP: "OTP မရရှိပါသလား?",
  RESEND_OTP: "ပြန်ပို့ရန်",
  EXPIRED: "OTP သက်တမ်းကုန်ဆုံးပါပြီ",
  "FAILED_TO_ENTER_OTP_3_TIMES._PLEASE_CONTACT_CALL_CENTER_09796629662.":
    "OTP သုံးကြိမ်မှားယွင်းပါသည်။ Customer Care Center ၀၉၇၉၆၆၂၉၆၆၂ သို့ဆက်သွယ်ပါ။",
  CREATE_YOUR_USERNAME: "အသုံးပြုသူအမည် သတ်မှတ်ရန်",
  YOMA_BANK_NEXT_PORTAL_8_25_CHARACTERS_ALLOWED:
    "Yoma Bank Next Portal ကို login ၀င်ရန် စာလုံးနှင့် ကိန်းဂဏန်း ၈လုံးမှ ၂၅လုံးရှိပြီး တအထူးအကမပါ၀င်သော အသုံးပြုသူအမည်ထည့်ပါ။ ",
  USERNAME: "အသုံးပြုသူအမည်",
  ENTER_USERNAME: "အသုံးပြုသူအမည် ထည့်ပါ",
  USERNAME_IS_TOO_SHORT: "အသုံးပြုသူအမည် တိုတောင်းနေသဖြင့် အဆင်မပြေပါ။",
  USERNAME_CAN_ONLY_CONTAIN:
    "အသုံးပြုသူအမည်တွင် အက္ခရာစာလုံးအသေး နှင့် ဂဏန်းများသာပါဝင်နိုင်ပါသည် (a-z ၊ 0-9)",
  CREATE_PASSWORD: "စကားဝှက်သတ်မှတ်ရန်",
  FOR_SECURITY_CHARACTERS:
    "စကားဝှက်တွင် စာလုံးအကြီး၊ စာလုံးအသေး၊ ကိန်းဂဏန်းနှင့် အထူးအက္ခရာ ၈လုံးမှ ၁၆လုံးထိ ပါဝင်ရမည်။",
  AT_LEAST_ONE_UPPERCASE_LETTER: "အနည်းဆုံး စာလုံးအကြီးတစ်လုံး",
  AT_LEAST_ONE_LOWERCASE_LETTER: "အနည်းဆုံး  စာလုံးအသေးတစ်လုံး",
  AT_LEAST_ONE_NUMBER: "အနည်းဆုံး ဂဏန်းတစ်လုံး",
  AT_LEAST_ONE_SPECIAL_CHARACTER: "အနည်းဆုံး  အထူးအက္ခရာတစ်လုံး",
  "SUFFICIENT_LENGTH_(8_16_CHARACTERS)":
    "သတ်မှတ်ထားသော စာလုံးအရေအတွက် (၈လုံး မှ ၁၆လုံး)",
  PASSWORD: "လျှို့ဝှက်ကုတ်နံပါတ်",
  ENTER_PASSWORD: "စကားဝှက် ထည့်ပါ",
  CONFIRM_PASSWORD: "စကားဝှက်အသစ်  အတည်ပြုပါ",
  REGISTRATION_SUCCESSFUL: "စာရင်းသွင်းခြင်း အောင်မြင်ပါပြီ",
  SUCCESSFULLY_REGISTERED:
    "စာရင်းသွင်းခြင်း အောင်မြင်စွာ ပြီးဆုံးပါပြီ။ Login ဝင်ရောက်ရန် ဆက်လက်လုပ်ဆောင်ပါ။",
  GO_TO_LOGIN: "Login သို့သွားပါ",
  REGISTRATION_FAILED: "စာရင်းသွင်းခြင်း မအောင်မြင်ပါ",
  "CANT_CONNECT_TO_REGISTRATION_SERVER_AND_COULD_NOT_BE_COMPLETED!.":
    "ဆာဗာနှင့် မချိတ်ဆက်နိုင်၍ စာရင်းသွင်းခြင်း မလုပ်ဆောင်နိုင်ပါ",
  "SORRY_SOMETHING_WENT_WRONG._PLEASE_TRY_AGAIN.":
    "တစ်ခုခုမှားယွင်းနေပါသဖြင့် ထပ်မံကြိုးစားပေးပါ။",
  PLEASE_TRY_AGAIN: "နောက်တစ်ကြိမ် လုပ်ဆောင်ပါ",
  FORGOT_PASSWORD: "လျှို့ဝှက်ကုတ်နံပါတ်ကိုမေ့နေပါသလား?",
  LOGIN: "ဝင်မည်",
  NATIONAL_ID: "မှတ်ပုံတင်အမှတ်",
  MOBILE_NUMBER: "မိုဘိုင်းလ်ဖုန်းနံပါတ်",
  LESSLESS_BACK_TO_LOGIN: "Login သို့ပြန်သွားရန်",
  UPDATE_PASSWORD: "Update password",
  "YOU_NEED_TO_CHANGE_YOUR_PASSWORD.": " You need to change your password.",
  NEW_PASSWORD: "New Password",
  ENTER_NEW_PASSWORD: "Enter New Password",
  RE_TYPE_NEW_PASSWORD: "Re-type New Password",
  UPDATE: "Update",
  "INVALID_PASSWORD:_MUST_NOT_BE_EQUAL_TO_ANY_OF_LAST_3_PASSWORDS.":
    "Invalid password: must not be equal to any of last 3 passwords.",
  DASHBOARD: "ပင်မစာမျက်နှာ",
  ACCOUNT_OVERVIEW: "ဘဏ်စာရင်းများ",
  FIXED_DEPOSIT: "Fixed Deposit",
  LOANS: "ချေးငွေအချက်အလက်များ",
  TRANSFER: "ငွေလွှဲရန်",
  OWN_ACCOUNT_TRANSFER: "မိမိအကောင့်သို့ငွေလွှဲရန်",
  OTHER_ACCOUNT_TRANSFER: "အခြားအကောင့်သို့ငွေလွှဲရန်",
  OTHER_BANK_TRANSFER: "အခြားဘဏ်သို့ငွေလွှဲရန်",
  WAVEPAY_TRANSFER: "WavePay Transfer",
  TRANSACTION_HISTORY: "ငွေလွှဲပြောင်းမှုမှတ်တမ်းများ",
  RECEIVERS: "ငွေလွှဲလက်ခံသူများ",
  BILL_PAYMENT: "ဘေလ်ပေးဆောင်ရန်",
  MOBILE_TOP_UP: "ဖုန်းငွေဖြည့်ရန်",
  BULK_PAYMENT: "အစုလိုက်ငွေလွှဲပြောင်းရန်",
  BULK_TRANSACTION_HISTORY: "အစုလိုက်ငွေလွှဲပြောင်းမှုမှတ်တမ်းများ",
  SCHEDULE_PAYMENT: "ငွေပေးချေမှုကြိုတင်စီစဉ်ရန်",
  APPROVALS: "အတည်ပြုရန်",
  CHANGE_LANGUAGE: "ဘာသာစကားပြောင်းရန်",
  LOGOUT: "ထွက်ရန်",
  NOTIFICATIONS: "အသိပေးချက်များ",
  ALL: "အသိပေးချက်များအားလုံး",
  NEWS_AND_PROMOTIONS: "သတင်း နှင့် ပရိုမိုးရှင်း အသိပေးချက်များ",
  ACCOUNT_INFROMATION: "အကောင့်နှင့် ဆိုင်သော အသိပေးချက်များ",
  SYSTEM_INFORMATION: "စနစ်နှင့် ဆိုင်သော  အသိပေးချက်များ",
  NO_NOTIFICATIONS: "အသိပေးချက်များမရှိပါ။",
  SESSION_EXPIRED: "ဝင်ရောက်အသုံးပြုနိုင်မည့် သက်တမ်းကုန်ဆုံးသွားပါပြီ။",
  "YOUR_SESSION_TIMED_OUT._PLEASE_SIGN_IN_AGAIN.":
    "သင်၏အသုံးပြုနိုင်မည့် အချိန်ကုန်ဆုံးသွားပါပြီ။ ကျေးဇူးပြု၍နောက်တစ်ကြိမ်ပြန်ဝင်ပါ။",
  OK: "အိုကေ",
  NO_INTERNET_CONNECTION: "အင်တာနက်ချိတ်ဆက်မှုမရှိပါ",
  "PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN.":
    "ကျေးဇူးပြု၍အင်တာနက်ချိတ်ဆက်မှုကို စစ်ဆေးပြီး ပြန်စမ်းကြည့်ပါ။",
  WELCOME_BACK: "ပြန်လည်ကြိုဆိုပါသည်",
  MY_ACCOUNTS: "ကျွန်ုပ်၏ အကောင့်စာရင်းများ",
  RECENT_TRANSACTIONS: "လတ်တလောငွေလွှဲပြောင်းမှုများ",
  "ACC_NO.": "အကောင့်နံပါတ်",
  TRANSACTION_INITIATED_DATE: "ငွေလွှဲပြောင်းမှုလုပ်ဆောင်သည့်နေ့",
  TRANSACTION_REFERENCE_ID: "ငွေကြေးလုပ်ဆောင်ချက် ရည်ညွန်းအမှတ်",
  TRANSACTION_AMOUNT: "ငွေလွှဲပြောင်းမည့်ပမာဏ",
  FROM: "မှ",
  TO: "သို့",
  TRANSACTION_TYPE: "ငွေကြေးလုပ်ဆောင်မှုအမျိုးအစား",
  THERE_IS_NO_TRANSACTION_YET: "ငွေကြေးလုပ်ဆောင်မှု မရှိသေးပါ။",
  DEPOSIT: "အပ်ငွေစာရင်းများ",
  YOU_DONT_HAVE_ANY_ACTIVE_DEPOSIT_ACCOUNTS:
    "You don't have any active Deposit Accounts",
  ACC_NO: "အကောင့်နံပါတ်",
  ACCOUNT_DETAIL: "အကောင့်အသေးစိတ် အချက်အလက်များ ",
  DOWNLOAD_ACCOUNT_STATEMENT: "ဘဏ်စာရင်းရှင်းတမ်းဒေါင်းလုဒ်လုပ်ရန်",
  ACCOUNT_NO: "အကောင့်နံပါတ်",
  ACCOUNT_NAME: "အကောင့်အမည်",
  ACCOUNT_HOLDER_NAME: "အကောင့်ပိုင်ရှင်အမည်",
  AVAILABLE_BALANCE: "လွှဲနိုင်သည့်ပမာဏ",
  ACCOUNT_CURRENCY: "ငွေကြေးအမျိုးအစား",
  INTEREST_RATE: "အတိုးနှုန်း",
  BLOCKED_AMOUNT: "လွှဲမရသည့်ပမာဏ",
  BOOKED_BALANCE: "စာရင်းရှိပမာဏ",
  ACCOUNT_TYPE: "အကောင့်အမျိုးအစား",
  OPENING_DATE: "အကောင့်ဖွင့်သည့်နေ့",
  ACCOUNT_STATUS: "အကောင့်အခြေအနေ",
  BACK: "Back",
  TRANSACTION_LIST: "ငွေကြေးလုပ်ဆောင်ချက်စာရင်းများ",
  FROM_DATE: "ရက်စွဲမှ",
  TO_DATE: "ရက်စွဲသို့",
  SEARCH: "ရှာမည်",
  CLEAR_ALL: "အားလုံးရှင်းမည်",
  DOWNLOAD_ACCOUNT_STATEMENTS_LAST_12_MONTHS:
    "လွန်ခဲ့သော ၁၂လ၏စာရင်းရှင်းတမ်းကို လအလိုက် ရွေးချယ်ကာ ဒေါင်းလုဒ်လုပ်နိုင်ပါသည်",
  PLEASE_CHOOSE_MONTH: "လကိုရွေးချယ်ပါ",
  DOWNLOAD: "ဒေါင်းလုဒ်လုပ်မည်",
  CANCEL: "Cancel",
  "DOWNLOADING_......": "ဒေါင်းလုဒ်လုပ်နေပါသည် .........",
  DOWNLOAD_SUCCESSFULLY: "ဒေါင်းလုဒ်လုပ်ခြင်းအောင်မြင်ပါသည်",
  CHANGE_YOUR_ACCOUNT_NAME: "အကောင့်နာမည်ပြောင်းမည်",
  ACCOUNT_RENAME: "အကောင့်နာမည် ပြန်လည်သတ်မှတ်ပါ",
  ENTER_ACCOUNT_NAME: "အကောင့်နာမည် ထည့်ပါ",
  SAVE: "Save",
  TRANSACTION_ID: "Transaction ID",
  MESSAGE: "မှတ်ချက်",
  PURPOSE_OF_TRANSACTION: "ငွေလွှဲပြောင်းမှုရည်ရွယ်ချက်",
  TRANSFER_FEES: "ငွေလွှဲ၀န်ဆောင်ခ",
  REMARK: "မှတ်ချက်",
  RECEIVER_BANK_NAME: "လက်ခံသူဘဏ်နာမည်",
  RECEIVER_BRANCH_NAME: "လက်ခံသူဘဏ်ခွဲနာမည်",
  FIXED_DEPOSIT_ACCOUNT: "Fixed Deposit Account",
  "GROW_YOUR_SAVINGS_NOW_BY_OPENING_A_FIXED_DEPOSIT_ACCOUNT_WITH_THE_INTEREST_RATE_OF_8.25PERCENT_P.A.":
    "Grow your savings now by opening a Fixed Deposit account with the interest rate of 8.25% p.a.",
  "GROW_YOUR_SAVINGS_NOW_BY_OPENING_A_SUPER_FIXED_DEPOSIT_ACCOUNT_WITH_THE_HIGHEST_INTEREST_RATE_OF_9.75PERCENT_P.A_TRANSFERRING_FROM_A_FLEXI_EVERYDAY_ACCOUNT.":
    "Grow your savings now by opening a Super Fixed Deposit account with the highest interest rate of 9.75% p.a, transferring from a Flexi Everyday account.",
  CLICK_HERE_TO_OPEN_AN_ACCOUNT: "စာရင်းသေအပ်ငွေစာရင်းဖွင့်ရန် ဤနေရာကိုနှိပ်ပါ",
  OPEN_FIXED_DEPOSIT_ACCOUNT: "စာရင်းသေအပ်ငွေစာရင်းဖွင့်မည်",
  "EARN_MORE_INTEREST_WITH_FIXED_DEPOSIT_ACCOUNT!":
    "Earn More interest with Fixed Deposit Account!",
  TOTAL_INTEREST: "အတိုးနှုန်း စုစုပေါင်း",
  "TOTAL_INTEREST_IS_:": "အတိုးနှုန်း စုစုပေါင်း",
  INTEREST_PAY_OUT_ACCOUNT: "အတိုးထည့်သွင်းမည့် အကောင့်",
  SUPER_FIXED_DEPOSIT_ACCOUNT: "Super စာရင်းသေအပ်ငွေစာရင်း",
  OPEN_SUPER_FIXED_DEPOSIT_ACCOUNT: "Super စာရင်းသေအပ်ငွေစာရင်းဖွင့်မည်",
  FROM_WHICH_ACCOUNT: "အသုံးပြုမည့်အကောင့်",
  DEPOSIT_AMOUNT: "အပ်ငွေ အမျိုးအစား",
  ENTER_AMOUNT: "အပ်ငွေ ပမာဏရိုက်ထည့်ပါ။",
  DEPOSIT_CONDITIONS: "အပ်ငွေအခြေအနေ",
  MATURITY: "စာရင်းသက်တမ်းပြည့်မည့်အချိန်",
  MATURITY_INFO: "Maturity Info",
  "MATURITY_METHODS_CAN_BE_EFFECTIVE_IF_YOUR_NEW_FIXED_DEPOSIT_ACCOUNT_IS_DUE.":
    "Maturity methods can be effective if your new fixed deposit account is due.",
  PRINCIPAL_ONLY_ROLLOVER: "အရင်းသက်တမ်းတိုးမည်",
  "INTEREST_WILL_BE_PAYOUT_TO_YOUR_SOURCE_ACCOUNT_(OR)_SELECTED_ACCOUNT_AND_PRINCIPAL_WILL_BE_RENEWAL_FOR_THE_NEXT_TERM.":
    "Interest will be payout to your source account (or) selected account and Principal will be renewal for the next term.",
  NO_ROLLOVER: "တိုးရင်းပေါင်းထုတ်မည်",
  "PRINCIPAL_AND_INTEREST_WILL_BE_PAYOUT_TO_YOUR_ACCOUNT.":
    "Principal and Interest will be payout to your account.",
  "PRINCIPAL+INTEREST_ROLLOVER": "တိုးရင်းပေါင်း သက်တမ်းတိုးမည်",
  "BOTH_PRINCIPAL_AND_INTEREST_AMOUNT_WILL_BE_RENEWAL_FOR_THE_NEXT_TERM.":
    "Both principal and interest amount will be renewal for the next term.",
  CLOSE: "Close",
  "TOTAL_PAYBACK_AMOUNT_WILL_BE_50308.21_MMK_AND_INTEREST_WILL_BE_308.21_MMK.":
    "စုစုပေါင်းပြန်ရမည့် ပမာဏမှာ ( ) ကျပ် ဖြစ်သည်။",
  TOTAL_PAYBACK_AMOUNT: "စုစုပေါင်းပြန်ရမည့် ပမာဏ",
  "INTEREST_AMOUNT_WILL_BE_MMK.": "အတိုးပမာဏမှာ ( ) ကျပ်ဖြစ်သည်။",
  DEPOSIT_TYPE: "အပ်ငွေ ပမာဏ",
  MATURITY_DATE: "စာရင်းသက်တမ်းပြည့်မည့်နေ့",
  "PRINCIPAL_WILL_BE_PAID_TO_YOUR_SOURCE_ACCOUNT.":
    "Principal will be paid to your source account.",
  CONFIRM: "အတည်ပြုမည်။",
  "SUCCESSFULLY_CREATED_YOUR_FIXED_DEPOSIT_ACCOUNT!":
    "စာရင်းသေအပ်ငွေစာရင်း အောင်မြင်စွာဖွင့်လှစ်ပြီးပါပြီ။",
  "MINIMUM_TRANSACTION_AMOUNT_SHOULD_BE_50000.00_MMK.":
    "အနည်းဆုံး ၅၀,၀၀၀ ကျပ်ဖြင့် အပ်ငွေစာရင်းဖွင့်လှစ်ရပါမည်",
  SORRY: "ဝမ်းနည်းပါတယ်",
  "YOURE_NOT_FLEXI_ACCOUNT_USER!":
    "လူကြီးမင်းသည် Flexi Account အသုံးပြုသူမဟုတ်ပါ",
  VERIFY_YOUR_TRANSACTION: "Verify Your Transaction",
  ENTER_ONE_TIME_PASSWORD_TO_CONFIRM_YOUR_TRANSFER:
    "Enter One Time Password to confirm your transfer",
  "ONE_TIME_PASSWORD_IS_SENT_TO_YOUR_REGISTERED_MOBILE_NUMBER._PLEASE_ENTER_THE_CODE_IN_THE_MESSAGE_TO_AUTHENTICATE_YOURSELF.":
    "One time password is sent to your registered mobile number. Please enter the code in the message to authenticate yourself.",
  "OTP_WILL_BE_EXPIRED_IN_2:49": "OTP will be expired in 2:49",
  "OTP_EXPIRED!": "OTP Expired!",
  DONT_RECEIVE_THE_OTP_RESEND_ONE_TIME_PASSWORD:
    "Don't receive the OTP? Resend-One Time Password",
  LOANS_INFO: "ချေးငွေအချက်အလက်များ",
  LOAN_ACCOUNT_NO: "ချေးငွေအကောင့်နံပါတ်",
  "YOU_DO_NOT_HAVE_ANY_ACTIVE_LOAN.": "မည်သည့်ချေးငွေမှ မရှိပါ။",
  "THERE_IS_NO_REPAYMENT_YET.": "ပေးဆောင်ထားခြင်းမရှိသေးပါ။",
  LOAN_DETAIL: "ချေးငွေအသေးစိတ်အချက်အလက်များ",
  DISBURSEMENT_DATE: "ချေးငွေထုတ်ပေးသည့်ရက်စွဲ",
  LOAN_AMOUNT: "ချေးငွေပမာဏ",
  LOAN_TERMS: "ချေးငွေကာလ",
  CURRENCY: "ငွေကြေးအမျိုးအစား",
  LOAN_STATUS: "ချေးငွေအခြေအနေ",
  SUMMARY: "အနှစ်ချုပ် အချက်အလက်များ",
  LOAN_TYPE: "ချေးငွေအမျိုးအစား",
  REPAYMENT_TYPE: "ပေးဆောင်ရမည့်အမျိုးအစား",
  REPAYMENT_FREQUENCY: "ပေးဆောင်ရမည့်အကြိမ်ရေ",
  NEXT_REPAYMENT_AMOUNT: "နောက်တစ်ကြိမ်ပေးဆောင်ရမည့်ပမာဏ",
  NEXT_REPAYMENT_DATE: "နောက်တစ်ကြိမ်ပေးဆောင်ရမည့်နေ့",
  OVERDUE_DAYS: "ရက်လွန်ရက်များ",
  LAST_PAID_DATE: "နောက်ဆုံးပေးဆောင်သည့်ရက်စွဲ",
  OVERDUE_AMOUNT: "ရက်လွန်ပမာဏ",
  PENALTY: "ဒဏ်ငွေ",
  REPAYMENT_SCHEDULE: "ပြန်ဆပ်ရမည့်အချိန်ဇယား",
  PAYMENT_DUE_ON: "ပေးချေရမည့်ရက်",
  REPAYMENT_NO: "ပေးဆောင်ရမည့်အကြိမ်ရေ",
  REPAYMENT_AMOUNT: "ပေးဆောင်ရမည့်ပမာဏ",
  INTEREST: "အတိုးပမာဏ",
  PRINCIPAL: "အရင်းစုစုပေါင်း",
  STATUS: "အခြေအနေ",
  SEARCH_BY_STATUS: "အခြေအနေအလိုက်ရှာဖွေမည်",
  PAID: "ပေးဆောင်ပြီး",
  UNPAID: "မပေးဆောင်ရသေးပါ",
  UPCOMING: "မကြာမီပေးဆောင်ရန်",
  TRANSACTION_DETAIL: "ငွေလွှဲပြောင်းမှုအသေးစိတ်မှတ်တမ်းများ",
  TRANSACTION_DATE: "ငွေလွှဲပြောင်းမှုလုပ်ဆောင်သည့်နေ့",
  DOWNLOAD_TRANSACTION: "ဒေါင်းလုဒ်လုပ်မည်",
  AMOUNT: "ပမာဏ",
  YOMA_BANK_NEXT_ACTIVATION: "YOMA BANK NEXT အကောင့်ဖွင့်ရန်",
  ENTER_YOMA_BANK_ACCOUNT_AND_NRC_OR_PASSPORT_NUMBER:
    "သင်၏ရိုးမဘဏ်အကောင့်နှင့် မှတ်ပုံတင်နံပါတ် သို့မဟုတ် နိုင်ငံကူးလက်မှတ်ထည့်ရန်",
  PLEASE_PROVIDE_THE_FOLLOWING_INFORMATION_TO_REGISTER:
    "စာရင်းသွင်းရန် အောက်ပါအချက်များကို ဖြည့်စွက်ပါ",
  OTP_WILL_BE_EXPIRED_IN_0245: "02:45 တွင် OTP သက်တမ်းကုန်ဆုံးပါမည်",
  ENTER_USERNAME_TO_LOGIN_TO_YOMA_BANK_NEXT_PORTAL_8_25_CHARACTERS_ALLOWED_ALPHA_NUMERIC_NO_SPECIAL_CHARACTERS_ALLOWED:
    "Yoma Bank Next Portal ကို login ၀င်ရန် စာလုံးနှင့် ကိန်းဂဏန်း ၈လုံးမှ ၂၅လုံးရှိသည့် အထူးအက္ခရာမပါ၀င်သော အသုံးပြုသူအမည်ထည့်ပါ။ ",
  USERNAME_CAN_ONLY_CONTAIN_LOWERCASE_LETTERS_AND_NUMBERS__A_Z_0_9:
    "အသုံးပြုသူအမည်တွင် အက္ခရာစာလုံးအသေး နှင့် ဂဏန်းများသာပါဝင်နိုင်ပါသည် (a-z ၊ 0-9)",
  FOR_SECURITY_USE_8_16_CHARACTERS_WITH_UPPERCASE_LOWERCASE_NUMBER_AND_SPECIAL_CHARACTERS:
    "စကားဝှက်တွင် စာလုံးအကြီး၊ စာလုံးအသေး၊ ကိန်းဂဏန်းနှင့် အထူးအက္ခရာ ၈လုံးမှ ၁၆လုံးထိ ပါဝင်ရမည်။",
  SUFFICIENT_LENGTH__8_16_CHARACTERS:
    "သတ်မှတ်ထားသော စာလုံးအရေအတွက် (၈လုံး မှ ၁၆လုံး)",
  YOU_HAVE_BEEN_SUCCESSFULLY_REGISTERED_AND_CONTIMUE_TO_LOGIN:
    "စာရင်းသွင်းခြင်း အောင်မြင်စွာ ပြီးဆုံးပါပြီ။ Login ဝင်ရောက်ရန် ဆက်လက်လုပ်ဆောင်ပါ။",
  YOU_NEED_TO_CHANGE_YOUR_PASSWORD: "စကားဝှက်ပြောင်းရန် လိုပါမည်",
  NEW_PASSWORD: "စကားဝှက်အသစ်",
  ENTER_NEW_PASSWORD: "စကားဝှက်အသစ် ထည့်ပါ",
  RE_TYPE_NEW_PASSWORD: "စကားဝှက်အသစ်  ပြန်ထည့်ပါ",
  UPDATE: "ပြင်ဆင်မည်",
  DASHBOARD: "ပင်မစာမျက်နှာ",
  ACCOUNT_OVERVIEW: "ဘဏ်စာရင်းများ",
  FIXED_DEPOSIT: "စာရင်းသေအပ်ငွေများ",
  LOANS: "ချေးငွေအချက်အလက်များ",
  TRANSFER: "ငွေလွှဲမည်",
  OWN_ACCOUNT_TRANSFER: "မိမိအကောင့်သို့ငွေလွှဲရန်",
  OTHER_ACCOUNT_TRANSFER: "အခြားအကောင့်သို့ငွေလွှဲရန်",
  OTHER_BANK_TRANSFER: "အခြားဘဏ်သို့ငွေလွှဲရန်",
  WAVEPAY_TRANSFER: "WavePay အကောင့်သို့ငွေလွှဲရန်",
  TRANSACTION_HISTORY: "ငွေလွှဲပြောင်းမှုမှတ်တမ်းများ",
  RECEIVERS: "ငွေလွှဲလက်ခံသူများ",
  BILL_PAYMENT: "ဘေလ်ပေးဆောင်ခြင်း",
  MOBILE_TOP_UP: "ဖုန်းငွေဖြည့်ရန်",
  BULK_PAYMENT: "အစုလိုက်ငွေလွှဲပြောင်းရန်",
  BULK_TRANSACTION_HISTORY: "အစုလိုက်ငွေလွှဲပြောင်းမှုမှတ်တမ်းများ",
  SCHEDULE_PAYMENT: "ငွေပေးချေမှုကြိုတင်စီစဉ်ရန်",
  APPROVALS: "အတည်ပြုရန်",
  CHANGE_LANGUAGE: "ဘာသာစကားပြောင်းရန်",
  LOGOUT: "ထွက်ရန်",
  NOTIFICATIONS: "အသိပေးချက်များ",
  ALL: "အသိပေးချက်များအားလုံး",
  NEWS_AND_PROMOTIONS: "သတင်း နှင့် ပရိုမိုးရှင်း အသိပေးချက်များ",
  ACCOUNT_INFROMATION: "အကောင့်နှင့် ဆိုင်သော အသိပေးချက်များ",
  SYSTEM_INFORMATION: "စနစ်နှင့် ဆိုင်သော  အသိပေးချက်များ",
  NO_NOTIFICATIONS: "အသိပေးချက်များမရှိပါ။",
  WELCOME_BACK: "ပြန်လည်ကြိုဆိုပါသည်",
  MY_ACCOUNTS: "ကျွန်ုပ်၏ အကောင့်စာရင်းများ",
  RECENT_TRANSACTIONS: "လတ်တလောငွေလွှဲပြောင်းမှုများ",
  ACC_NO: "အကောင့်နံပါတ်",
  TRANSACTION_INITIATED_DATE: "ငွေလွှဲပြောင်းမှုလုပ်ဆောင်သည့်နေ့",
  TRANSACTION_REFERENCE_ID: "ငွေကြေးလုပ်ဆောင်ချက် ရည်ညွန်းအမှတ်",
  TRANSACTION_AMOUNT: "ငွေလွှဲပြောင်းမည့်ပမာဏ",
  FROM: "မှ",
  TO: "သို့",
  TRANSACTION_TYPE: "ငွေကြေးလုပ်ဆောင်မှုအမျိုးအစား",
  THERE_IS_NO_TRANSACTION_YET: "ငွေကြေးလုပ်ဆောင်မှု မရှိသေးပါ။",
  DEPOSIT: "အပ်ငွေစာရင်းများ",
  YOU_DONT_HAVE_ANY_ACTIVE_DEPOSIT_ACCOUNTS:
    "သင့်တွင် လက်ရှိအပ်ငွေစာရင်းများ မရှိပါ။",
  ACCOUNT_DETAIL: "အကောင့်အသေးစိတ် အချက်အလက်များ ",
  DOWNLOAD_ACCOUNT_STATEMENT: "အကောင့်စာရင်း ဒေါင်းလုဒ်လုပ်မည်",
  ACCOUNT_NAME: "အကောင့်အမည်",
  ACCOUNT_HOLDER_NAME: "အကောင့်ပိုင်ရှင်အမည်",
  AVAILABLE_BALANCE: "လွှဲနိုင်သည့်ပမာဏ",
  ACCOUNT_CURRENCY: "ငွေကြေးအမျိုးအစား",
  INTEREST_RATE: "အတိုးနှုန်း",
  BLOCKED_AMOUNT: "လွှဲမရသည့်ပမာဏ",
  BOOKED_BALANCE: "စာရင်းရှိပမာဏ",
  ACCOUNT_TYPE: "အကောင့်အမျိုးအစား",
  OPENING_DATE: "အကောင့်ဖွင့်သည့်နေ့",
  ACCOUNT_STATUS: "အကောင့်အခြေအနေ",
  MORE_DETAIL: "အသေးစိတ်ကြည့်မည်။",
  TRANSACTION_LIST: "ငွေကြေးလုပ်ဆောင်ချက်စာရင်းများ",
  FROM_DATE: "ရက်စွဲမှ",
  TO_DATE: "ရက်စွဲသို့",
  SEARCH: "ရှာမည်",
  CLEAR_ALL: "အားလုံးရှင်းမည်",
  YOU_COULD_ONLY_DOWNLOAD_ACCOUNT_STATEMENTS_THAT_ARE_VALID_FOR_THE_LAST_12_MONTHS:
    "လွန်ခဲ့သော ၁၂လ၏စာရင်းရှင်းတမ်းကို လအလိုက် ရွေးချယ်ကာ ဒေါင်းလုဒ်လုပ်နိုင်ပါသည်",
  PLEASE_CHOOSE_MONTH: "လကိုရွေးချယ်ပါ",
  DOWNLOAD: "ဒေါင်းလုဒ်လုပ်မည်",
  CANCEL: "မလုပ်တော့ပါ",
  DOWNLOADING_: "ဒေါင်းလုဒ်လုပ်နေပါသည် .........",
  DOWNLOAD_SUCCESSFULLY: "ဒေါင်းလုဒ်လုပ်ခြင်းအောင်မြင်ပါသည်",
  CHANGE_YOUR_ACCOUNT_NAME: "အကောင့်နာမည်ပြောင်းမည်",
  ACCOUNT_RENAME: "အကောင့်နာမည် ပြန်လည်သတ်မှတ်ပါ",
  ENTER_ACCOUNT_NAME: "အကောင့်နာမည် ထည့်ပါ",
  SAVE: "သိမ်းဆည်းမည် ",
  TRANSACTION_ID: "ငွေလွှဲသည့်အမှတ်",
  MESSAGE: "မှတ်ချက်",
  PURPOSE_OF_TRANSACTION: "ငွေလွှဲပြောင်းမှုရည်ရွယ်ချက်",
  TRANSFER_FEES: "ငွေလွှဲ၀န်ဆောင်ခ",
  REMARK: "မှတ်ချက်",
  RECEIVER_BANK_NAME: "လက်ခံသူဘဏ်နာမည်",
  RECEIVER_BRANCH_NAME: "လက်ခံသူဘဏ်ခွဲနာမည်",
  FIXED_DEPOSIT_ACCOUNT: "စာရင်းသေအပ်ငွေစာရင်းများ",
  GROW_YOUR_SAVINGS_NOW_BY_OPENING_A_FIXED_DEPOSIT_ACCOUNT_WITH_THE_INTEREST_RATE_OF_825PERCENT_PA:
    "ရိုးမဘဏ်ရဲ့ အတိုးနှုန်း ၈.၂၅% p.a အထိ ရရှိနိုင်မည့် Fixed Deposit ကို စာရင်းဖွင့်ပြီး သင်၏ စုဆောင်းငွေကို တိုးပွားအောင် ပြုလုပ်လိုက်ပါ",
  GROW_YOUR_SAVINGS_NOW_BY_OPENING_A_SUPER_FIXED_DEPOSIT_ACCOUNT_WITH_THE_HIGHEST_INTEREST_RATE_OF_975PERCENT_PA_TRANSFERRING_FROM_A_FLEXI_EVERYDAY_ACCOUNT:
    "ရိုးမဘဏ်ရဲ့ အမြင့်ဆုံး အတိုးနှုန်း ၉.၇၅% p.a အထိ ရရှိနိုင်မည့် Super Fixed Deposit ကို Flexi Everyday အကောင့်မှ လွှဲပြောင်း၍ စာရင်းဖွင့်ပြီး သင်၏ စုဆောင်းငွေကို တိုးပွားအောင် ပြုလုပ်လိုက်ပါ",
  CLICK_HERE_TO_OPEN_AN_ACCOUNT: "စာရင်းသေအပ်ငွေစာရင်းဖွင့်ရန် ဤနေရာကိုနှိပ်ပါ",
  OPEN_FIXED_DEPOSIT_ACCOUNT: "စာရင်းသေအပ်ငွေစာရင်းဖွင့်မည်",
  "EARN_MORE_INTEREST_WITH_FIXED_DEPOSIT_ACCOUNT!":
    "စာရင်းသေအပ်ငွေစာရင်းဖွင့်ပြီး သင်၏ စုဆောင်းငွေကို တိုးပွားအောင် ပြုလုပ်လိုက်ပါ!",
  TOTAL_INTEREST: "အတိုးနှုန်း စုစုပေါင်း",
  TOTAL_INTEREST_IS_: "အတိုးနှုန်း စုစုပေါင်း",
  INTEREST_PAY_OUT_ACCOUNT: "အတိုးထည့်သွင်းမည့် အကောင့်",
  SUPER_FIXED_DEPOSIT_ACCOUNT: "Super စာရင်းသေအပ်ငွေစာရင်း",
  OPEN_SUPER_FIXED_DEPOSIT_ACCOUNT: "Super စာရင်းသေအပ်ငွေစာရင်းဖွင့်မည်",
  FROM_WHICH_ACCOUNT: "အသုံးပြုမည့်အကောင့်",
  DEPOSIT_AMOUNT: "အပ်ငွေ အမျိုးအစား",
  ENTER_AMOUNT: "အပ်ငွေ ပမာဏရိုက်ထည့်ပါ။",
  DEPOSIT_CONDITIONS: "အပ်ငွေအခြေအနေ",
  MATURITY: "စာရင်းသက်တမ်းပြည့်မည့်အချိန်",
  MATURITY_INFO: "စာရင်းသက်တမ်းအမျိုးအစား",
  MATURITY_METHODS_CAN_BE_EFFECTIVE_IF_YOUR_NEW_FIXED_DEPOSIT_ACCOUNT_IS_DUE:
    "သင်၏ fixed deposit သက်တမ်းပြည့်သည့်နေ့အတွက် ဆက်လက်လုပ်ဆောင်ရမည့် ညွှန်ကြားချက် ဖြစ်သည်။",
  PRINCIPAL_AND_INTEREST_WILL_BE_PAYOUT_TO_YOUR_ACCOUNT:
    "အရင်းနှင့်အတိုးအား သင်၏မူရင်းအကောင့်ထဲသို့ ပြန်ထည့်မည်။",
  INTEREST_WILL_BE_PAYOUT_TO_YOUR_SOURCE_ACCOUNT__OR_SELECTED_ACCOUNT_AND_PRINCIPAL_WILL_BE_RENEWAL_FOR_THE_NEXT_TERM:
    "အတိုးအား သင်၏ မူရင်းအကောင့် (သို့မဟုတ်) ရွေးချယ်ထားသောအကောင့်ထဲသို့ ပြန်ထည့်ပြီး အရင်းအား fixed deposit သက်တမ်းအသစ်ဖြင့် ဆက်ထားမည်။",
  BOTH_PRINCIPAL_AND_INTEREST_AMOUNT_WILL_BE_RENEWAL_FOR_THE_NEXT_TERM:
    "အရင်းနှင့်အတိုး အားလုံးပေါင်းပမာဏအား fixed deposit သက်တမ်းအသစ်ဖြင့် ဆက်ထားမည်။",
  TOTAL_PAYBACK_AMOUNT_WILL_BE_5030821_MMK_AND_INTEREST_WILL_BE_30821_MMK:
    "စုစုပေါင်းပြန်ရမည့် ပမာဏမှာ ( 50,308.21 ) ကျပ် ဖြစ်ပြီး အတိုး ပမာဏမှာ ( 308.21 ) ကျပ် ဖြစ် သည်။",
  TOTAL_PAYBACK_AMOUNT: "Total Payback Amount",
  DEPOSIT_TYPE: "အပ်ငွေ ပမာဏ",
  MATURITY_DATE: "စာရင်းသက်တမ်းပြည့်မည့်‌နေ့",
  PRINCIPAL_WILL_BE_PAID_TO_YOUR_SOURCE_ACCOUNT:
    "အရင်းအားသင်၏ မူရင်းအကောင့်ထဲသို့ ထည့်မည်။",
  BACK: "အရှေ့သို့ပြန်သွားရန်",
  CONFIRM: "အတည်ပြုမည်။",
  "SUCCESSFULLY_CREATED_YOUR_FIXED_DEPOSIT_ACCOUNT!":
    "စာရင်းသေအပ်ငွေစာရင်း အောင်မြင်စွာဖွင့်လှစ်ပြီးပါပြီ။",
  MINIMUM_TRANSACTION_AMOUNT_SHOULD_BE_5000000_MMK:
    "အနည်းဆုံး ၅၀,၀၀၀ ကျပ်ဖြင့် အပ်ငွေစာရင်းဖွင့်လှစ်ရပါမည်",
  SORRY: "ဝမ်းနည်းပါတယ်",
  "YOURE_NOT_FLEXI_ACCOUNT_USER!":
    "လူကြီးမင်းသည် Flexi Account အသုံးပြုသူမဟုတ်ပါ",
  LOANS_INFO: "ချေးငွေအချက်အလက်များ",
  LOAN_ACCOUNT_NO: "ချေးငွေအကောင့်နံပါတ်",
  YOU_DO_NOT_HAVE_ANY_ACTIVE_LOAN: "မည်သည့်ချေးငွေမှ မရှိပါ။",
  THERE_IS_NO_REPAYMENT_YET: "ပေးဆောင်ထားခြင်းမရှိသေးပါ။",
  LOAN_DETAIL: "ချေးငွေအသေးစိတ်အချက်အလက်များ",
  DISBURSEMENT_DATE: "ချေးငွေထုတ်ပေးသည့်ရက်စွဲ",
  LOAN_AMOUNT: "ချေးငွေပမာဏ",
  LOAN_TERMS: "ချေးငွေကာလ",
  CURRENCY: "ငွေကြေးအမျိုးအစား",
  LOAN_STATUS: "ချေးငွေအခြေအနေ",
  SUMMARY: "အနှစ်ချုပ် အချက်အလက်များ",
  LOAN_TYPE: "ချေးငွေအမျိုးအစား",
  REPAYMENT_TYPE: "ပေးဆောင်ရမည့်အမျိုးအစား",
  REPAYMENT_FREQUENCY: "ပေးဆောင်ရမည့်အကြိမ်ရေ",
  NEXT_REPAYMENT_AMOUNT: "နောက်တစ်ကြိမ်ပေးဆောင်ရမည့်ပမာဏ",
  NEXT_REPAYMENT_DATE: "နောက်တစ်ကြိမ်ပေးဆောင်ရမည့်နေ့",
  OVERDUE_DAYS: "ရက်လွန်ရက်များ",
  LAST_PAID_DATE: "နောက်ဆုံးပေးဆောင်သည့်ရက်စွဲ",
  OVERDUE_AMOUNT: "ရက်လွန်ပမာဏ",
  PENALTY: "ဒဏ်ငွေ",
  REPAYMENT_SCHEDULE: "ပြန်ဆပ်ရမည့်အချိန်ဇယား",
  PAYMENT_DUE_ON: "ပေးချေရမည့်ရက်",
  REPAYMENT_NO: "ပေးဆောင်ရမည့်အကြိမ်ရေ",
  REPAYMENT_AMOUNT: "ပေးဆောင်ရမည့်ပမာဏ",
  INTEREST: "အတိုးပမာဏ",
  PRINCIPAL: "အရင်းစုစုပေါင်း",
  STATUS: "အခြေအနေ",
  SEARCH_BY_STATUS: "အခြေအနေအလိုက်ရှာဖွေမည်",
  PAID: "ပေးဆောင်ပြီး",
  UNPAID: "မပေးဆောင်ရသေးပါ",
  UPCOMING: "မကြာမီပေးဆောင်ရန်",
  TRANSACTION_DETAIL: "ငွေလွှဲပြောင်းမှုအသေးစိတ်မှတ်တမ်းများ",
  TRANSACTION_DATE: "ငွေလွှဲပြောင်းမှုလုပ်ဆောင်သည့်နေ့",
  DOWNLOAD_TRANSACTION: "ဒေါင်းလုဒ်လုပ်မည်",
  TO_WHICH_ACCOUNT: "လက်ခံမည့်အကောင့်သို့",
  AMOUNT: "ငွေပမာဏ",
  OPTIONAL: "မဖြည့်လဲရပါသည်",
  OWN_ACCOUNT_TRANSFER_REVIEW: "မိမိအကောင့်သို့ငွေလွှဲပြောင်းခြင်းကိုစစ်ဆေးရန်",
  WHAT_YOU_NEED_TO_KNOW_BEFORE_SENDING_THIS_MONEY:
    "ငွေမလွှဲခင် သိထားသင့်သည်များ",
  TRANSFER_AMOUNT: "ငွေလွှဲမည့်ပမာဏ",
  OWN_ACCOUNT_TRANSFERS_ARE_ALWAYS_FREE:
    "ကိုယ်ပိုင်အကောင့်အချင်းချင်းအခမဲ့ငွေလွှဲနိုင်ပါသည်",
  TOTAL_DEBIT_AMOUNT: "စုစုပေါင်းငွေပမာဏ",
  BY_CLICKING_CONFIRM_YOU_AGREE_TO_THE_TERMS_AND_CONDITIONS:
    "အတည်ပြုမည်ကိုနှိပ်လိုက်ခြင်းအားဖြင့်စည်းကမ်းသတ်မှတ်ချက်များကိုသိရှိနားလည်ပြီးဖြစ်ပါသည်",
  TERMS_AND_CONDITIONS: "စည်းကမ်းသတ်မှတ်ချက်များ",
  YOUR_TRANSFER_IS_SUCCESSFUL: "သင်၏ဘေလ်ပေးဆောင်ခြင်းအောင်မြင်ပါသည်။",
  SEE_TRANSACTION_HISTORY: "ငွေလွှဲပြောင်းမှုမှတ်တမ်း ကြည့်မည်။",
  BACK_TO_DASHBOARD: "ပင်မစာမျက်နှာသို့ သွားမည်၊",
  DOWNLOAD_RECEIPT: "ငွေလွှဲဖြတ်ပိုင်းကို ဒေါင်းလုဒ်လုပ်ပါ။",
  TRANSACTION_FAILED: "လုပ်ဆောင်ချက်မအောင်မြင်ပါ။",
  ENTER_ACCOUNT_NUMBER: "အကောင့်နံပါတ်ကိုထည့်ပါ",
  RECEIVER_LIST: "ငွေလွှဲလက်ခံသူစာရင်း",
  SEARCH_RECEIVER_NAME: "ငွေလွှဲလက်ခံသူကိုရှာဖွေရန်",
  NO_RESULTS_FOUND: "ရှာမတွေ့ပါ။",
  ENTER_REMARK: "မှတ်ချက်ကိုထည့်ပါ",
  TRANSFER_FEES_WILL_BE_CHARGED_ON_SOME_ACCOUNT_TYPES:
    "အချို့သော အကောင့်အမျိုးအစားများမှ ငွေလွှဲပြောင်းခြင်းအတွက် ငွေလွှဲဝန်ဆောင်ခ ကောက်ခံပါမည်။",
  OTHER_ACCOUNT_TRANSFER_REVIEW:
    "အခြားအကောင့်သို့ငွေလွှဲပြောင်းခြင်းကိုစစ်ဆေးရန်",
  SAVE_RECEIVER: "ငွေလွှဲလက်ခံသူကိုသိမ်းဆည်းရန်",
  RECEIVER_NAME: "ငွေလွှဲလက်ခံသူနာမည်",
  ADD_RECEIVER: "ငွေလွှဲလက်ခံသူသိမ်းမည်။",
  PAYMENT_TYPE: "ငွေပေးချေမှုအမျိုးအစား",
  TRANSFER_TO: "ငွေလွှဲမည့်ဘဏ်သို့",
  SELECT_BANK: "ဘဏ်ကိုရွေးပါ",
  ENTER_RECEIVER_NAME: "ငွေလွှဲလက်ခံသူနာမည်ကိုထည့်ပါ",
  RECEIVER_ACCOUNT_NUMBER: "ငွေလွှဲလက်ခံသူအကောင့်နံပါတ်",
  ENTER_RECEIVER_ACCOUNT_NUMBER: "ငွေလွှဲလက်ခံသူအကောင့်နံပါတ်ကိုထည့်ပါ",
  BRANCH_NAME: "ဘဏ်ခွဲနာမည်\t",
  SELECT_BRANCH: "ဘဏ်ခွဲကိုရွေးပါ",
  SELECT_RECIPIENT: "ငွေလွှဲလက်ခံသူကိုရွေးချယ်ရန်",
  SEARCH_RECIPIENT: "ငွေလွှဲလက်ခံသူကိုရှာဖွေရန်",
  PHONE_NUMBER: "မိုဘိုင်းလ်ဖုန်းနံပါတ်",
  ENTER_RECEIVER_PHONE_NUMBER: "ငွေလွှဲလက်ခံသူမိုဘိုင်းလ်ဖုန်းနံပါတ်ကိုထည့်ပါ",
  YOU_CAN_ONLY_MAKE_TRANSFERS_BETWEEN_930_AM_TO_230_PM_ON_BANK_WORKING_DAYS:
    "ဘဏ်ဖွင့်ရက်များတွင် နံနက် ၉း၃၀ မှ နေ့လည် ၂း၃၀ အတွင်းသာ လွှဲပြောင်းနိုင်ပါသည်။",
  OTHER_BANK_TRANSFER_REVIEW: "အခြားဘဏ်သို့ငွေလွှဲပြောင်းခြင်းကိုစစ်ဆေးရန်",
  NOTE: "မှတ်သားရန်",
  YOUR_TRANSFER_IS_INITIATED: "ငွေလွှဲပြောင်းခြင်းကိုစတင်လုပ်ဆောင်နေပါသည်။",
  RECEIVER_NICKNAME: "နာမည်တို",
  BANK_NAME: "ဘဏ်နာမည်\t",
  MOBILE_TOP_UP_REVIEW: "ဖုန်းငွေဖြည့်ခြင်းကိုစစ်ဆေးရန်",
  TOP_UP_TO: "ငွေဖြည့်ရန်",
  TOP_UP_AMOUNT: "ငွေဖြည့်ပမာဏ",
  TOP_UP_FEES: "ငွေဖြည့်ခ",
  DISCOUNT: "လျှော့ဈေး",
  MOBILE_TOP_UP_IS_SUCCESSFUL: "သင်၏ဖုန်းငွေဖြည့်ခြင်းအောင်မြင်ပါသည်။",
  BROWSE_BY_CATEGORY: "‌ဘေလ်အမျိုးအစားအလိုက်ရှာရန်",
  INTERNET: "အင်တာနက်",
  GOVERNMENT_AND_ELECTRICITY_METER_BILLS: "အစိုးရနှင့်လျှပ်စစ်ဓာတ်အားမီတာခ",
  INSURANCE_AND_HEALTH: "အာမခံနှင့်ကျန်းမာရေး",
  BUSINESS: "စီးပွားရေးလုပ်ငန်း",
  ENTERTAINMENT_AND_DIGITAL_COUPON: "ဖျော်ဖြေရေးနှင့်ဒစ်ဂျစ်တယ်ကူပွန်",
  MICROFINANCE_AND_RE_PAYMENT: "အသေးစားငွေကြေးနှင့်ချေးငွေပြန်ဆပ်ခြင်း",
  TRAVEL_AND_TOURS: "ခရီးသွားလုပ်ငန်း",
  ONLINE_SHOPPING: "အွန်လိုင်းဈေးဝယ်ခြင်း",
  EDUCATION: "ပညာရေး",
  PROPERTY_PAYMENT: "အိမ်မြေငွေပေးချေမှု",
  OTHERS: "အခြား",
  SEARCH_BILLERS: "‌ဘေလ်ပေးဆောင်ရန်ရှာမည်",
  BILLER_LIST: "‌ဘေလ်စာရင်းများ",
  BILL_PAYMENT_REVIEW: "ဘေလ်ပေးဆောင်ခြင်းကိုစစ်ဆေးရန်",
  BILL_REFERENCE_ID: "ဘေလ်လုပ်ဆောင်ချက် ရည်ညွှန်းအမှတ်",
  YOMA_BANK: "ရိုးမဘဏ်",
  WAVEPAY: "WavePay",
  OTHER_BANK: "အခြားဘဏ်",
  WAVEPAY_ACCOUNT_NUMBER: "WavePay အကောင့်နံပါတ်",
  ENTER_RECEIVER_NICKNAME: "ငွေလွှဲလက်ခံသူနာမည်တို ထည့်ပါ",
  ENTER_DIGITIS: "အကောင့်နံပါတ်ကိုထည့်ပါ",
  SUCCESS: "အောင်မြင်ပါသည်",
  "SAVE_SUCCESSFULLY!": "အောင်မြင်စွာသိမ်းဆည်းပြီးပါပြီ",
  YOU_HAVE_SUCCESSFULLY_SAVED_RECEIVER:
    "‌ငွေလက်ခံသူကိုအောင်မြင်စွာသိမ်းဆည်းပြီးပါပြီ။",
  GO_TO_RECEIVER_LIST:
    "ငွေလွှဲလက်ခံသူအားလုံးကိုသိမ်းဆည်းထားသောစာရင်းသို့သွားရန်",
  NAME: "ငွေလွှဲလက်ခံသူနာမည်",
  ACTION: "လုပ်ဆောင်ရန်",
  EDIT_RECEIVER: "ငွေလွှဲလက်ခံသူကိုပြင်ဆင်ရန်",
  DELETE_RECEIVER: "ငွေလွှဲလက်ခံသူကိုဖျက်သိမ်းရန်",
  DELETE: "ဖျက်သိမ်းမည်",
  ARE_YOU_SURE_YOU_WANT_TO_DELETE:
    "ငွေလွှဲလက်ခံသူကိုဖျက်သိမ်းလိုသည်မှာသေချာပါသလား?",
  THIS_WILL_DELETE_YOUR_RECIPIENT_FROM_THE_LIST:
    "ငွေလွှဲလက်ခံသူကိုစာရင်းမှဖျက်သိမ်းလိုက်ပါမည်။",
  THERE_IS_NO_RECIPIENT_S: "ငွေလွှဲလက်ခံသူ(များ)မရှိပါ။",
  EDIT: "ပြင်ဆင်မည်",
  TRANSFER_TO_OWN_ACCOUNT: "မိမိအကောင့်သို့ငွေလွှဲရန်",
  TRANSFER_TO_OTHER_ACCOUNT: "အခြားအကောင့်သို့ငွေလွှဲရန်",
  TRANSFER_TO_OTHER_BANK: "အခြားဘဏ်သို့ငွေလွှဲရန်",
  TRANSFER_TO_WAVEPAY: "WavePay အကောင့်သို့ငွေလွှဲရန်",
  PAY_BILLS: "ဘေလ်ပေးဆောင်ရန်",
  SAVED_RECEIVERS: "သိမ်းဆည်းထားသော ငွေလက်ခံသူများကြည့်ရန်",
  OPEN_A_FIXED_DEPOSIT_ACCOUNT: "စာရင်းသေအပ်ငွေစာရင်းဖွင့်ရန်",
  PROMOTIONS_MARKETING_CAMPAIGN: "ပရိုမိုးရှင်း/ကမ်ပိန်းများကြည့်ရန်",
  YOUR_TRANSFER_AMOUNT_WILL_RECEIVE_WITHIN_24_36_HOURS:
    "ငွေလွှဲလိုက်သည့် ပမာဏကို ၂၄ နာရီမှ ၃၆ နာရီအတွင်း ရရှိမည်ဖြစ်ပါသည်။",
  WAVE_ACCOUNT_TRANSFER: "Wave အကောင့်သို့ ငွေလွှဲရန်",
  WAVE_ACCOUNT: "Wave အကောင့်",
  VERIFY_YOUR_TRANSACTION: "ငွေလွှဲပြောင်းခြင်းကိုစိစစ်ရန်",
  ENTER_ONE_TIME_PASSWORD_TO_CONFIRM_YOUR_TRANSFER:
    "ငွေလွှဲပြောင်းခြင်းကိုစိစစ်ရန်တစ်ခါသုံးကုဒ်ကိုရိုက်ထည့်ပါ။",
  ONE_TIME_PASSWORD_IS_SENT_TO_YOUR_REGISTERED_MOBILE_NUMBER_PLEASE_ENTER_THE_CODE_IN_THE_MESSAGE_TO_AUTHENTICATE_YOURSELF:
    "တစ်ခါသုံးကုဒ်ကိုစာရင်းသွင်းထားသောမိုလ်ဘိုင်းဖုန်းနံပါတ်သို့ပို့မည်ဖြစ်ပါသည်။ကျေးဇူးပြု၍ပေးပို့လာသောတစ်ခါသုံးကုဒ်ကိုစစ်မှန်ကြောင်းသက်သေပြရန်ရိုက်ထည့်ပါ။",
  OTP_WILL_BE_EXPIRED_IN_138: "OTP will be expired in 1:38",
  INVALID_OTP: "တစ်ခါသုံးစကားဝှက်မှားယွင်းနေပါသည်။",
  EXPIRED_OTP: "တစ်ခါသုံးစကားဝှက်သက်တမ်းမှာ ကုန်ဆုံးသွားပါပြီ။",
  SOMETHING_WENT_WRONG: "လုပ်ဆောင်မှုမှားယွင်းနေပါသည်။\r\n",
  "OTP_EXPIRED!": "တစ်ခါသုံးစကားဝှက်သက်တမ်းမှာ ကုန်ဆုံးသွားပါပြီ။",
  DONT_RECEIVE_THE_OTP_RESEND_ONE_TIME_PASSWORD:
    "OTP ကို ​​မရပါသလား? နောက်တစ်ကြိမ် တစ်ခါသုံးစကားဝှက်ကို ပြန်ပို့ပါ။",
  DONT_RECEIVE_THE_OTP_RESEND_OTP: "OTP မရရှိပါသလား?",
  EXPIRED: "OTP သက်တမ်းကုန်ဆုံးပါပြီ",
  FAILED_TO_ENTER_OTP_3_TIMES_PLEASE_CONTACT_CALL_CENTER_09796629662:
    "OTP သုံးကြိမ်မှားယွင်းပါသည်။ Customer Care Center ၀၉၇၉၆၆၂၉၆၆၂ သို့ဆက်သွယ်ပါ။",
  FAMILY_SUPPORT: "မိသားစု ထောက်ပံ့ခြင်း",
  SALARIES: "လစာဝင်ငွေ",
  TAX_PAYMENT: "အခွန်ပေးဆောင်ခြင်း",
  INSURANCE_PAYMENT: "အာမခံပေးဆောင်ခြင်း",
  LOAN_REPAYMENT: "ချေးငွေပြန်လည်ပေးဆပ်ခြင်း",
  LOAN_DISBURSEMENT: "ချေးငွေထုတ်ယူခြင်း",
  CUSTOM_DUTY: "အကောက်ခွန်ပေးဆောင်ခြင်း",
  COMPANY_FUND_TRANSFER: "လုပ်ငန်းသုံးငွေအား ပြောင်းရွှေ့ခြင်း",
  RENTAL: "ငှားရမ်းခ ပေးချေ/ ထုတ်ယူခြင်း",
  SALE_PROCEED: "ရောင်းချရရှိငွေ",
  DONATION: "အလှူငွေ",
  PURCHASE_GOLD_JEWELRY: "ရွှေနှင့်ကျောက်မျက်ရတနာဝယ်ယူခြင်း",
  COST_OF_GOODS: "ကုန်ဖိုးငွေပေးချေခြင်း/ ထုတ်ယူခြင်း",
  GENERAL_EXPENSES: "အထွေထွေကုန်ကျစရိတ် ",
  PURCHASE: "ပစ္စည်းဝယ်ယူခြင်း",
  SERVICE_CONSULTANT_FEES: "ဝန်ဆောင်မှု/ အကြံပေးဝန်ဆောင်မှု",
  HIGH_VALUE_ASSETS: "တန်ဖိုးမြင့်ပစ္စည်း ရောင်းဝယ်ခြင်း",
  OTHER: "အခြား ",
  PLEASE_FILL_THE_TYPE_OF_ITEMS_PURCHASED__EG_ONLINE_SHOPPING_CAR_HOUSE_FARMS_LAND_ETC:
    "ငှါးရမ်းသည့် ပစ္စည်းအမျိုးအစား (ဥပမာ ကား၊အိမ်၊ခြံမြေ၊တိုက်ခန်း၊စသည့်ဖြင့်)",
  PLEASE_FILL_THE_TYPE_OF_ITEMS_SOLD__EG_CAR_HOUSE_LAND_APARTMENTS_GOODS_ETC:
    "ရောင်းချခဲ့သော ပစ္စည်းအမျိုးအစား (ဥပမာ ကား၊အိမ်၊ခြံမြေ၊တိုက်ခန်း၊ကုန်ပစ္စည်း စသည်ဖြင့်)",
  PLEASE_FILL_THE_PURPOSE_OF_DONATION: "လှူဒါန်းမည့်အကြောင်းအရာအားဖြည့်စွက်ရန်",
  PLEASE_FILL_THE_TYPE_OF_GOODS_PAID__EG_BEAN_IRON_BETEL_NUT_BUILDING_MATERIALS_ETC:
    "ပေးချေသော ကုန်ဖိုးပစ္စည်းအမျိုးအစား (ဥပမာ ပဲ၊သံ၊ကွမ်း၊ဆောက်လုပ်ရေးပစ္စည်း စသည်ဖြင့်)",
  PLEASE_FILL_GENERAL_COSTS__EG_HEALTH_EDUCATION_ETC:
    "အထွေထွေကုန်ကျစရိတ် (ဥပမာ ကျန်းမာရေး၊ ပညာရေး စသည်ဖြင့်)",
  PLEASE_FILL_PURCHASED_GOLDJEWELLERY:
    "ဝယ်ယူသော ပစ္စည်းအမျိုးအစား (ဥပမာ online shopping၊ကား၊အိမ်၊ခြံ၊မြေ စသည်ဖြင့်)",
  PLEASE_FILL_THE_TYPE_OF_SERVICEADVISORY_SERVICE__EG_MAINTENANCE_FEES_LEGAL_ADVISORY_FEES:
    "ဝန်ဆောင်မှုအမျိုးအစား/အကြံပေးဝန်ဆောင်မှု (ဥပမာ maintenance fees၊ ဥပဒေ အကြံပေးဝန်ဆောင်ခစသည်ဖြင့်)",
  PLEASE_FILL_OTHER_COSTS: "မှတ်ချက်ဖြည့်သွင်းပါ။",
  THE_PASSWORD_CANNOT_CONTAIN_SPACES: "စကားဝှက်တွင် space ပါ၍မရပါ။",
  PASSWORDS_DO_NOT_MATCH: "စကားဝှက် ကိုက်ညီမှုမရှိပါ။",
  THIS_FIELD_MUST_BE_AT_LEAST_8_CHARACTERS:
    "ဤနေရာတွင် စာလုံးအနည်းဆုံးရှစ်လုံးပါရမည်။",
  THIS_FIELD_IS_REQUIRED: "ဤနေရာကို ဖြည့်သွင်းပါ။\t这是必填栏",
  FILTER_TRANSACTION_TYPE: "ငွေကြေးလုပ်ဆောင်မှုအမျိုးအစားကိုကြည့်ရန်။",
  ONLY_ALLOW_ENGLISH_CHARACTER: "အင်္ဂလိပ်အက္ခရာကိုသာခွင့်ပြုပါသည်။",
  PLEASE_ENTER_A_VALID_AMOUNT: "ကျေးဇူးပြု၍ မှန်ကန်သောပမာဏကို ထည့်ပါ။",
  MORE_DETAILS: "အသေးစိတ်အချက်အလက်များ",
  MATURITY_INSTRUCTIONS: "Maturity Instructions",
  INTEREST_AMOUNT: "Interest Amount",
  INTEREST_PAYBACK_ACCOUNT: "Interest Payback Account",
  PRINCIPAL_PAYBACK_ACCOUNT: "Principal Payback Account",
  ORIGINAL_AMOUNT: "Original Amount",
  USERNAME_IS_TOO_SHORT: "အသုံးပြုသူအမည် တိုတောင်းနေသဖြင့် အဆင်မပြေပါ။",
  REGISTRATION_FAILED: "စာရင်းသွင်းခြင်း မအောင်မြင်ပါ",
  SORRY_SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN:
    "တစ်ခုခုမှားယွင်းနေပါသဖြင့် ထပ်မံကြိုးစားပေးပါ။",
  YOU_DO_NOT_HAVE_SUFFICIENT_BALANCE: "ငွေပမာဏလုံလောက်မှုမရှိပါ။",
  PER_TRANSACTION_LIMIT_IS_EXCEEDED_THAN_500000000_MMK:
    "ငွေလွှဲပမာဏမှာ သတ်မှတ်ထားသော 5,000,000.00 MMK ထက်ကျော်လွန်နေပါသည်",
  MINIMUM_TRANSACTION_AMOUNT_SHOULD_BE_100_MMK:
    "အနည်းဆုံးလွှဲပြောင်းမည့်ငွေပမာဏ ၁ကျပ်ဖြစ်ရပါမည်။",
  PLEASE_ENTER_VALID_ACCOUNT_NUMBER:
    "ကျေးဇူးပြု၍ မှန်ကန်သောအကောင့်နံပါတ်ကို ထည့်ပါ။",
  "ACCOUNT_NOT_FOUND!": "အကောင့်နံပါတ်ရှာမတွေ့ပါ။",
  'ONLY_INDIVIDUAL_FLEXI_ACCOUNT_IS_ALLOWED_FOR_TRANSFER_PLEASE_WALK_IN_TO_THE_NEAREST_YOMA_BRANCHES__OR_CLICK_ON_"ACCOUNT_OVERVIEW_GREATER_OPEN_FLEXI_EVERYDAY_ACCOUNT"_IN_NEXT_PORTAL_TO_OPEN_FLEXI_ACCOUNT!':
    'မိမိတဦးတည်းပိုင် Flexi Account ဖြင့်သာ ငွေလွှဲနိုင်ပါမည်။ ကျေးဇူးပြု၍ အနီးဆုံး Yomaဘဏ်ခွဲများသို့ သွားရောက်၍ Flexi အကောင့်ကို ဖွင့်ပါ။ (သို့မဟုတ်) Next Portal ထဲရှိ Account Overview tab တွင် "Flexi Everyday အကောင့်ဖွင့်ရန်" ကို နှိပ်ပြီး Flexi အကောင့်ကို ဖွင့်ပါ။',
  PLEASE_ENTER_THE_VALID_MOBILE_NUMBER:
    "ကျေးဇူးပြု၍ မှန်ကန်သောမိုဘိုင်းဖုန်းနံပါတ်ကို ထည့်ပါ။",
  SORRY_YOUR_OTHER_ACCOUNT_TRANSFER_TRANSACTION_FAILED:
    "အခြားအကောင့်သို့ငွေလွှဲပြောင်းခြင်းမအောင်မြင်ပါ",
  SORRY_YOUR_MOBILE_TOP_UP_TRANSACTION_FAILED:
    "ဖုန်းငွေဖြည့်ခြင်းမအောင်မြင်ပါ။",
  BACK_TO_PAGE: "ငွေလွှမည့်  နေရာသို့ပြန်သွားရန်",
  YOUR_PHONE_NUMBER_IS_INVALID: "မိုဘိုင်းဖုန်းနံပါတ်မှားယွင်းနေပါသည်။",
  PLEASE_ENTER_VALID_NAME: "ကျေးဇူးပြု၍ စာရင်းသွင်းထားသောအမည်ထည့်ပါ။",
  PLEASE_ENTER_A_VALID_ACCOUNT_NUMBER:
    "ကျေးဇူးပြု၍မှန်ကန်သောအကောင့်နံပါတ်ကိုထည့်သွင်းပါ။\r\n",
  INVALID_PASSWORD_MUST_NOT_BE_EQUAL_TO_ANY_OF_LAST_3_PASSWORDS:
    "မမှန်ကန်သော စကားဝှက်- နောက်ဆုံး စကားဝှက် 3 ခုနှင့် မတူညီရပါ။",
  SESSION_EXPIRED: "ဝင်ရောက်အသုံးပြုနိုင်မည့် သက်တမ်းကုန်ဆုံးသွားပါပြီ။",
  YOUR_SESSION_TIMED_OUT_PLEASE_SIGN_IN_AGAIN:
    "သင်၏အသုံးပြုနိုင်မည့် အချိန်ကုန်ဆုံးသွားပါပြီ။ ကျေးဇူးပြု၍နောက်တစ်ကြိမ်ပြန်ဝင်ပါ။",
  OK: "အိုကေ",
  NO_INTERNET_CONNECTION: "အင်တာနက်ချိတ်ဆက်မှုမရှိပါ",
  PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN:
    "ကျေးဇူးပြု၍အင်တာနက်ချိတ်ဆက်မှုကို စစ်ဆေးပြီး ပြန်စမ်းကြည့်ပါ။",
  'SUPER_FIXED_DEPOSIT_CAN_BE_OPENED_BY_PAYMENT_WITH_FLEXI_ACCOUNTS_PLEASE_WALK_IN_TO_THE_NEAREST_YOMA_BRANCHES__OR_CLICK_ON_"ACCOUNT_OVERVIEW_GREATER_OPEN_FLEXI_EVERYDAY_ACCOUNT"_IN_NEXT_PORTAL_TO_OPEN_FLEXI_ACCOUNT!':
    'Flexi အကောင့်များဖြင့် ငွေပေးချေခြင်းဖြင့် Super Fixed Deposit ကို ဖွင့်နိုင်သည်။ ကျေးဇူးပြု၍ အနီးဆုံး Yomaဘဏ်ခွဲများသို့ သွားရောက်၍ Flexi အကောင့်ကို ဖွင့်ပါ။ (သို့မဟုတ်) Next Portal ထဲရှိ Account Overview tab တွင် "Flexi Everyday အကောင့်ဖွင့်ရန်" ကို နှိပ်ပြီး Flexi အကောင့်ကို ဖွင့်ပါ။',
};


